---
# tasks file for apache

- name: install apache
  ansible.builtin.yum:
    name: httpd
    state: present
- name: start the apache
  ansible.builtin.service:
    name: httpd
    state: started
- name: change the port of apache
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    notify:
      - restart the apache
      - name: chang the welocome page
        ansible.builtin.copy:
          src: index.html
          dest: /var/www/html
